# Gradio Chat UI configuration
port: 7860

mads:
  - name: pMAD Template
    url: http://pmad-template-langgraph:8000
    hostname: pmad-template-langgraph

# Health poll interval in seconds
health_poll_interval: 30
